TODO:
-----

gtd (command line client):

- now that mushin-hoodie added state (1 for active, 2 for archive),
  add that to our data model, with the enum.  Make sure all views handle
  an unset state as well.
- make it possible to work in 'hoodie mode' on a replica of a hoodie db
  (for example my mushin-hoodie local copy)

- add authentication support to replication
  - allow specifying username/password for remote host, parse it properly,
    without displaying it
  - allow asking for password of localhost
- don't use httplib for adding replication; add it to paisley.
- integrate paisley's use of logging with our logging
- convert all commands to using getNewServer()
- parse search lines and apply filters in most useful order
- Figure out what to do with docs without start date - maybe we have a bug
  introducing these ?
- add something to create the database first time
- fix delete 0sst
- fix delete:
GTD> del 9rozer
Unhandled error: [Failure instance: Traceback: <class 'twisted.web.error.Error'>: 409 {"error":"conflict","reason":"Document update conflict."}

/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py:1154:_bodyDataFinished_CONNECTED
/home/thomasvs/dev/own/mushin/python/mushin/extern/paisley/client.py:117:connectionLost
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:382:callback
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:490:_startRunCallbacks
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:577:_runCallbacks
/home/thomasvs/dev/own/mushin/python/mushin/extern/paisley/client.py:654:cb_process_resp
]

- bug when typing 'list' in cmd line interpreter - the error message is output
  on the same line as the command, instead of first getting a newline on stderr

- bug when specifying non-existent date:
GTD> add @parida @cft pilot ready to go by may 1st? D:2015-04-31
Unhandled error: [Failure instance: Traceback: <type 'exceptions.ValueError'>: day is out of range for month
/usr/lib/python2.7/dist-packages/twisted/conch/recvline.py:257:handle_RETURN
/home/thomasvs/dev/own/mushin/python/mushin/extern/command/manholecmd.py:271:lineReceived
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:139:maybeDeferred
/home/thomasvs/dev/own/mushin/python/mushin/extern/command/manholecmd.py:324:push
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:139:maybeDeferred
/usr/lib/python2.7/cmd.py:221:onecmd
/home/thomasvs/dev/own/mushin/python/mushin/extern/command/command.py:592:do_
/home/thomasvs/dev/own/mushin/python/mushin/extern/command/command.py:363:parse
/home/thomasvs/dev/own/mushin/python/mushin/common/tcommand.py:39:do
/home/thomasvs/dev/own/mushin/python/mushin/extern/command/tcommand.py:47:do
/home/thomasvs/dev/own/mushin/python/mushin/command/main.py:88:doLater
/home/thomasvs/dev/own/mushin/python/mushin/common/parse.py:134:parse
/home/thomasvs/dev/own/mushin/python/mushin/common/parse.py:174:parse_date
]

- deleting new thing fails:
GTD> delete xl99pdb4
Unhandled error: [Failure instance: Traceback: <class 'twisted.web.error.Error'>: 409 {"error":"conflict","reason":"Document update conflict."}

/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py:1154:_bodyDataFinished_CONNECTED
/home/thomasvs/dev/own/mushin/python/mushin/extern/paisley/client.py:117:connectionLost
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:382:callback
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:490:_startRunCallbacks
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:577:_runCallbacks
/home/thomasvs/dev/own/mushin/python/mushin/extern/paisley/client.py:654:cb_process_resp
]

- bad date fails:
GTD> add D:2015-11-31 p:money check if I got Q3 Mission Control bonus which should be about $7000 based on 3 weeks of 10% and 10 weeks of 20%
Unhandled error: [Failure instance: Traceback: <type 'exceptions.ValueError'>: day is out of range for month
/usr/lib/python2.7/dist-packages/twisted/conch/recvline.py:257:handle_RETURN
/home/thomasvs/dev/own/mushin/python/mushin/extern/command/manholecmd.py:271:lineReceived
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:139:maybeDeferred
/home/thomasvs/dev/own/mushin/python/mushin/extern/command/manholecmd.py:324:push
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:139:maybeDeferred
/usr/lib/python2.7/cmd.py:221:onecmd
/home/thomasvs/dev/own/mushin/python/mushin/extern/command/command.py:592:do_
/home/thomasvs/dev/own/mushin/python/mushin/extern/command/command.py:363:parse
/home/thomasvs/dev/own/mushin/python/mushin/common/tcommand.py:39:do
/home/thomasvs/dev/own/mushin/python/mushin/extern/command/tcommand.py:47:do
/home/thomasvs/dev/own/mushin/python/mushin/command/main.py:88:doLater
/home/thomasvs/dev/own/mushin/python/mushin/common/parse.py:134:parse
/home/thomasvs/dev/own/mushin/python/mushin/common/parse.py:174:parse_date
]


-mushin (maemo GUI):

- any exception from any gobject callback needs to be handled somehow with
  a dialog, to inform the user
- why does by-projects view also emit date in key ?
- new dialog:
  - no way to unset project/flag/... done does not click
- when completing a task, you go back to a list view where that task is still
  in there because it was not updated
- when completing a recurring task, the thing gets a new revision that should
  be gotten from couchdb, so that the next update on the same thing does not
  conflict.
- instead of getting the view of all projects on opening a task, keep it around
  and parse change notifications
- http://wiki.maemo.org/Phone_control#Make_a_phone_call_2

couchdb:
- by-*: agree on whether they list open or closed things
- decide on flags versus statuses

